server:
  port: 8081
spring:
  application:
    name: Data-Analysis
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
feign:
  okhttp:
    enabled: true